class Sql {
  static const String tables = """
CREATE TABLE USERW
(
	Email			TEXT PRIMARY KEY,
	Upassword		TEXT NOT NULL,
	Unumber			TEXT NOT NULL UNIQUE,
	Fname			TEXT NOT NULL,
	Mname			TEXT,
	Lname1			TEXT NOT NULL,
	Lname2			TEXT NOT NULL
);

CREATE TABLE STUDENT
(
	StudentID		TEXT PRIMARY KEY,
	University		TEXT NOT NULL,
	Miles			INTEGER DEFAULT 0,
	Uemail			TEXT NOT NULL,
	FOREIGN KEY (Uemail) REFERENCES USERW(Email)
);

CREATE TABLE AIRPORT
(
	AirportID			INTEGER PRIMARY KEY AUTOINCREMENT,
	Code				TEXT NOT NULL,
	City				TEXT NOT NULL,
	Aname				TEXT NOT NULL,
	Image				TEXT
);

CREATE TABLE PLANE
(
	PlaneID			TEXT PRIMARY KEY,
	Capacity		INTEGER NOT NULL
);

CREATE TABLE FLIGHT
(
	Fnumber			INTEGER PRIMARY KEY,
	Ffrom			INTEGER NOT NULL,
	Fto				INTEGER NOT NULL,
	Price			INTEGER NOT NULL,
	Fdate			TEXT NOT NULL,
	Fstate			INTEGER NOT NULL DEFAULT 0,
	Pid				TEXT NOT NULL,
	FOREIGN KEY (Pid) REFERENCES PLANE(PlaneID),
	FOREIGN KEY (Ffrom) REFERENCES AIRPORT(AirportID),
	FOREIGN KEY (Fto) REFERENCES AIRPORT(AirportID)
);

CREATE TABLE PASSENGER
(
	Uemail			TEXT PRIMARY KEY,
	Checked_in		INTEGER NOT NULL DEFAULT 0,
	Fno				INTEGER NOT NULL,
	FOREIGN KEY (Uemail) REFERENCES USERW(Email),
	FOREIGN KEY (Fno) REFERENCES FLIGHT(Fnumber)
);

CREATE TABLE PROMO
(
	Fno				INTEGER NOT NULL,
	Image			TEXT NOT NULL,
	Dpercent		INTEGER NOT NULL,
	Final_date		TEXT NOT NULL,
	PRIMARY KEY (Fno, Image),
	FOREIGN KEY (Fno) REFERENCES FLIGHT(Fnumber)
);

CREATE TABLE STOP
(
	StopID			INTEGER PRIMARY KEY AUTOINCREMENT,
	Sfrom			INTEGER NOT NULL,
	Sto				INTEGER NOT NULL,
	Sdate			TEXT NOT NULL,
	Departure_hour	TEXT NOT NULL,
	Arrival_hour	TEXT NOT NULL,
	Fno				INTEGER NOT NULL,
	FOREIGN KEY (Fno) REFERENCES FLIGHT(Fnumber),
	FOREIGN KEY (Sfrom) REFERENCES AIRPORT(AirportID),
	FOREIGN KEY (Sto) REFERENCES AIRPORT(AirportID)
);

CREATE TABLE SEAT
(
	Snumber			TEXT PRIMARY KEY,
	Sclass			TEXT DEFAULT 'general',
	Pemail			TEXT NOT NULL,
	Pid				TEXT NOT NULL,
	FOREIGN KEY (Pemail) REFERENCES PASSENGER(Uemail),
	FOREIGN KEY (Pid) REFERENCES PLANE(PlaneID)
);
"""
;
}
