class Sql {
  static const String tables = """CREATE TABLE USERW
(
	Email			VARCHAR(25)			NOT NULL,
	Upassword		VARCHAR(10)			NOT NULL,
	Unumber			CHAR(8)				NOT NULL,
	Fname			VARCHAR(10)			NOT NULL,
	Mname			VARCHAR(10),
	Lname1			VARCHAR(15)			NOT NULL,
	Lname2			VARCHAR(15)			NOT NULL,
	PRIMARY KEY (Email),
	UNIQUE (Email, Unumber)
);

-- STUDENT TABLE
CREATE TABLE STUDENT
(
	StudentID		CHAR(10)		NOT NULL,
	University		VARCHAR(30)		NOT NULL,
	Miles			INT				DEFAULT 0,
	Uemail			VARCHAR(25)		NOT NULL,
	PRIMARY KEY (StudentID)
);

-- FLIGHT TABLE
CREATE TABLE FLIGHT
(
	Fnumber		INT				NOT NULL,
	Ffrom		INT				NOT NULL,
	Fto			INT				NOT NULL,
	Price		INT				NOT NULL,
	Fdate		DATE			NOT NULL,
	Fstate		BOOLEAN			NOT NULL	DEFAULT 'false',
	Pid			CHAR(6)			NOT NULL,
	PRIMARY KEY (Fnumber)
);

-- PROMO TABLE
CREATE TABLE PROMO
(
	Fno			INT				NOT NULL,
	Image		VARCHAR(250)	NOT NULL,
	Dpercent	INT				NOT NULL,
	Final_date	DATE			NOT NULL,
	PRIMARY KEY (Fno, Image)
);

-- PLANE TABLE
CREATE TABLE PLANE
(
	PlaneID		CHAR(6)			NOT NULL,
	Capacity	INT				NOT NULL,
	PRIMARY KEY(PlaneID)
);

-- AIRPORT TABLE
CREATE TABLE AIRPORT
(
	AirportID			SERIAL			NOT NULL,
	Code				CHAR(3)			NOT NULL,
	City				VARCHAR(15)		NOT NULL,
	Aname				VARCHAR(50)		NOT NULL,
	Image				VARCHAR(250),
	PRIMARY KEY (AirportID)
);

-- STOP TABLE
CREATE TABLE STOP
(
	StopID				SERIAL			NOT NULL,
	Sfrom				INT				NOT NULL,
	Sto					INT				NOT NULL,
	Sdate				DATE			NOT NULL,
	Departure_hour		TIME			NOT NULL,
	Arrival_hour		TIME			NOT NULL,
	Fno					INT				NOT NULL,
	PRIMARY KEY (StopID)
);

-- FOREIGN KEYS
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_USER_FK FOREIGN KEY (Uemail)
REFERENCES USERW(Email);

ALTER TABLE FLIGHT
ADD CONSTRAINT FLIGHT_PLANE_FK FOREIGN KEY (Pid)
REFERENCES PLANE(PlaneID);

ALTER TABLE FLIGHT
ADD CONSTRAINT FLIGHT_FROM_AIRPORT_FK FOREIGN KEY (Ffrom)
REFERENCES AIRPORT(AirportID);

ALTER TABLE FLIGHT
ADD CONSTRAINT FLIGHT_TO_AIRPORT_FK FOREIGN KEY (Fto)
REFERENCES AIRPORT(AirportID);

ALTER TABLE PROMO
ADD CONSTRAINT PROMO_FLIGHT_FK FOREIGN KEY (Fno)
REFERENCES FLIGHT(Fnumber);

ALTER TABLE STOP
ADD CONSTRAINT STOP_FLIGHT_FK FOREIGN KEY (Fno)
REFERENCES FLIGHT(Fnumber);

ALTER TABLE STOP
ADD CONSTRAINT STOP_FROM_AIRPORT_FK FOREIGN KEY (Sfrom)
REFERENCES AIRPORT(AirportID);

ALTER TABLE STOP
ADD CONSTRAINT STOP_TO_AIRPORT_FK FOREIGN KEY (Sto)
REFERENCES AIRPORT(AirportID);""";
}